In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("datasets day 7/User_Data.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#extracting independent and dependent variable
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values
print(x[:10])

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]]


In [4]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25)

In [5]:
#feature scaling
from sklearn.preprocessing import StandardScaler
st_x=StandardScaler()
xtrain=st_x.fit_transform(xtrain)
xtest=st_x.transform(xtest)
print(xtrain[:10])
xtest=st_x.transform(xtest)

[[ 1.46320841  0.04197368]
 [ 0.22104193  0.1292169 ]
 [-0.73447074 -0.62689099]
 [ 0.3165932   0.47818977]
 [ 1.84541348  1.49602731]
 [ 0.603247   -0.91770172]
 [-1.68998342  0.4491087 ]
 [-0.73447074  0.24554119]
 [-0.35226567 -0.80137742]
 [-0.25671441  0.50727084]]


In [6]:
from sklearn.neighbors import KNeighborsClassifier
Classifier=KNeighborsClassifier(n_neighbors=5,metric="euclidean",p=2)
Classifier.fit(xtrain,ytrain)

KNeighborsClassifier(metric='euclidean')

In [7]:
y_pred=Classifier.predict(xtest)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [8]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(ytest,y_pred)
cm

array([[68,  0],
       [32,  0]], dtype=int64)

In [9]:
from sklearn.metrics import accuracy_score
print ("accuracy:",accuracy_score(ytest,y_pred))

accuracy: 0.68
