In [1]:
import pandas as pd
import numpy as np

In [3]:
dataset=pd.read_csv("datasets day 7/User_Data.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values

In [5]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25)

In [6]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
xtrain=sc_x.fit_transform(xtrain)
xtest=sc_x.transform(xtest)
print(xtrain[0:10, :])
print(xtest[0:10, :])

[[-1.33397653 -0.16836343]
 [ 0.3514407   0.09638978]
 [ 1.66232077  1.65549198]
 [-0.5849022  -1.58038052]
 [-0.21036504 -0.34486556]
 [ 0.07053783 -0.55078472]
 [-0.02309646 -0.34486556]
 [ 1.3814179  -0.90378899]
 [-0.77217078 -0.63903579]
 [-0.21036504 -0.40369961]]
[[-1.80214798  0.39056   ]
 [-0.5849022  -0.31544854]
 [ 0.81961216  1.4201558 ]
 [-1.05307365 -1.55096349]
 [ 1.10051503  0.5082281 ]
 [ 0.3514407   0.09638978]
 [ 0.16417212  1.09656855]
 [-0.02309646  0.18464085]
 [-1.14670794  0.53764512]
 [ 0.07053783  0.06697276]]


In [7]:
print(xtrain[:])
print(xtest[:])#for entire data

[[-1.33397653 -0.16836343]
 [ 0.3514407   0.09638978]
 [ 1.66232077  1.65549198]
 [-0.5849022  -1.58038052]
 [-0.21036504 -0.34486556]
 [ 0.07053783 -0.55078472]
 [-0.02309646 -0.34486556]
 [ 1.3814179  -0.90378899]
 [-0.77217078 -0.63903579]
 [-0.21036504 -0.40369961]
 [-0.86580507  0.53764512]
 [ 1.28778361 -1.34504434]
 [-0.95943936  2.00849625]
 [-1.33397653  0.39056   ]
 [ 0.16417212  1.92024519]
 [ 0.16417212  0.80239832]
 [-0.95943936  0.56706214]
 [-0.49126791 -1.49212945]
 [-0.77217078 -0.75670388]
 [-0.67853649  1.39073878]
 [ 1.47505219  0.39056   ]
 [-0.77217078  0.33172596]
 [ 1.84958935 -1.05087411]
 [ 0.25780641 -0.63903579]
 [ 0.44507499  1.0377345 ]
 [ 0.44507499  0.33172596]
 [ 0.25780641 -0.25661449]
 [-0.86580507 -0.93320602]
 [ 1.10051503 -1.19795922]
 [-0.11673075  1.44957282]
 [ 0.25780641  0.18464085]
 [-0.39763362 -0.25661449]
 [-0.77217078  0.41997703]
 [-0.67853649  1.94966221]
 [-1.6148794   0.15522382]
 [-1.24034223 -1.46271243]
 [-1.05307365 -0.49195068]
 

In [8]:
from sklearn.linear_model import LogisticRegression
Classifier=LogisticRegression(random_state=0)
Classifier.fit(xtrain,ytrain)

LogisticRegression(random_state=0)

In [9]:
import pickle
with open ("Logistic_model.pkl","wb") as files:
    pickle.dump(Classifier, files)
with open("Logistic_model.pkl","rb") as f:
    Classifier=pickle.load(f)
y_pred=Classifier.predict(xtest)
y_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [10]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(ytest,y_pred)
print("confusion matrix:\n" , cm)

confusion matrix:
 [[56  9]
 [ 8 27]]


In [11]:
from sklearn.metrics import accuracy_score
print("accuracy:", accuracy_score(ytest,y_pred))

accuracy: 0.83


In [12]:
from sklearn.metrics import precision_score
print("precision:", precision_score(ytest,y_pred))

precision: 0.75
